version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Ruta al frontend
      dockerfile: Dockerfile
    image: petropolis:latest
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://107.21.145.167:5001
    depends_on:
      - api
    networks:
      - app_network

  api:
    image: "node:22.9.0-alpine3.19"               
    environment:
      - VITE_API_URL=http://107.21.145.167:5001
    ports:
      - "5001:5001"                        
    volumes:
      - .:/home/node/nest                  
    depends_on:
      - db                                  
    networks:
      - app_network 

  db:
    image: "mysql:${DB_VERSION}"            
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS_ROOT}  
      MYSQL_DATABASE: ${DB_NAME}            
    volumes:
      - .mysql_data:/var/lib/mysql          
    ports:
      - "3307:3306"                         
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  .mysql_data:
    driver: local